package HTML_DIR::Model::Chado;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'HTML_DIR::Chado',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=chadodb;host=127.0.0.1',
        user => 'chadouser',
        password => '',
    }
);

=head1 NAME

HTML_DIR::Model::Chado - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<HTML_DIR>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<HTML_DIR::Chado>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

Wendel Hime L. Castro

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
