package html_dir::Model::Model;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'html_dir::Schema',
    
    connect_info => {
        dsn => 'dbi:SQLite:/home/wendelhlc/git/report_html_db/report_html_db/html_dir/database.db',
        user => '',
        password => '',
        on_connect_do => q{PRAGMA foreign_keys = ON},
    }
);

=head1 NAME

html_dir::Model::Model - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<html_dir>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<html_dir::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

Wendel Hime L. Castro

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
